
add_SE: true
alpha: 0.5
aug_add: 0.8
batch_size: 10240
dataset: age
device: cuda:0
dropout: 0.0
edge_drop: 0.99
epochs: 1000
eval_step: 5
gamma: 7.5
hid_dim: 512
in_drop: 0.3
info_loss_weight: 0.9
k: 10
loss: focal
loss_weight: null
lr: 0.0005
max_epochs: 500
model_name: HGT
n_data: 0
n_gnn: 1
n_mlp: 3
num_neigh: 10
num_train_per_class: 10
out_dim: 64
patient: 5
res_layer: false
se_min_count: 100
seed: 42
show_training: false
shuffle_attr: true
split: random
temperature: 0.07
use_jk: true
use_scheduler: false
weight_decay: 5.0e-05
use_drug_struct: false
drug_encoder_type: hybrid
drug_struct_dim: 128
drug_smiles_csv: new_data_in/refined_data/drugbank_id_smiles.csv
molformer_feat_path: ""
use_time_feature: false
time_dim: 32
